sapeim/urls.py
from django.conf.urls import url
from sapeim import views
from sapeim.views import AddElement, IndexView, UpdateElement, DeleteElement
from sapeim.views import ListBland, AddBland, DeleteBland, ListPrestamo, DetailPrestamo
from sapeim.views import ListElementType, AddElementType, DeleteElementType

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^add-elemento$', AddElement.as_view(), name='add-elemento'),
    url(r'^update-elemento/(?P<pk>\d+)$', UpdateElement.as_view(), name='up-elemento'),
    url(r'^delete-elemento/(?P<pk>\d+)$', DeleteElement.as_view(), name='delete-elemento'),
    url(r'^list-bland$', ListBland.as_view(), name='listar-marca'),
    url(r'^add-bland$', AddBland.as_view(), name='add-bland'),
    url(r'^delete-bland/(?P<pk>\d+)$', DeleteBland.as_view(), name='delete-bland'),
    url(r'^list-type$', ListElementType.as_view(), name='listar-tipoE'),
    url(r'^add-type$', AddElementType.as_view(), name='add-tipoE'),
    url(r'^delete-type/(?P<pk>\d+)$', DeleteElementType.as_view(), name='delete-tipoE'),
    url(r'^registro$', views.registro, name='registro'),
    url(r'^prestamos$', ListPrestamo.as_view(), name='list-prestamo'),
    url(r'^add-prestamo$', views.prestamo, name='add_prestamo'),
    url(r'^detail-prestamo/(?P<pk>\d+)$', DetailPrestamo.as_view(), name='detalle-pr'),
    url(r'^devoluciones/(?P<pk>\d+)$', views.devolucion, name='devoluciones'),
]

sena/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('sapeim.urls', namespace="sapeim")),
    url(r'^admin/', include(admin.site.urls)),
]

sapeim/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User


class Bland(models.Model):
    bland_name = models.CharField(max_length=60)

    def __str__(self):
        return self.bland_name


class Role(models.Model):
    role_name = models.CharField(max_length=50)

    def __str__(self):
        return self.role_name


class ElementType(models.Model):
    element_type = models.CharField(max_length=100)

    def __str__(self):
        return self.element_type


class Element(models.Model):
    bland = models.ForeignKey(Bland)
    element_type = models.ForeignKey(ElementType)
    opciones = ((1, 'Disponible'), (2, 'Ocupado'), (3, 'Mantenimiento'))
    state = models.IntegerField(choices=opciones, default=1)
    serial_sena = models.CharField(max_length=100)
    serial = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    features = models.TextField(blank=True)

    def __str__(self):
        return self.modelo


class UserProfile(models.Model):
    username = models.OneToOneField(User, unique=True)
    nombre = models.CharField(blank=True, max_length=100)
    apellido = models.CharField(blank=True, max_length=100)
    email = models.EmailField()
    opciones = ((1, 'CC'), (2, 'Pasaporte'), (3, 'TI'))
    document_type = models.IntegerField(choices=opciones, default=1)
    documento = models.IntegerField(unique=True)
    role = models.ForeignKey(Role)

    def __str__(self):
        return self.username.username


class Prestamo(models.Model):
    user = models.ForeignKey(UserProfile)
    fecha = models.DateField(default=datetime.datetime.today)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    devolucion = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)


class DetallePrestamo(models.Model):
    prestamo = models.ForeignKey(Prestamo)
    element = models.ForeignKey(Element)

    def __str__(self):
        return str(self.prestamo)

sapeim/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Element, Bland, UserProfile, Prestamo, DetallePrestamo


class AddElementForm(forms.ModelForm):

    class Meta:
        model = Element
        fields = ('bland', 'element_type', 'serial', 'serial_sena', 'modelo', 'features')


class AddBlandForm(forms.ModelForm):

    class Meta:
        model = Bland
        fields = ('bland_name',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('nombre', 'apellido', 'email', 'documento', 'document_type', 'role')


class PrestaForm(forms.ModelForm):

    class Meta:
        model = Prestamo
        fields = ('fecha', 'hora_inicio', 'hora_fin')


class PrestamoForm(forms.ModelForm):

    class Meta:
        model = Prestamo
        fields = ('fecha', 'hora_inicio', 'hora_fin', 'devolucion')


class DetalleForm(forms.ModelForm):

    class Meta:
        model = DetallePrestamo
        fields = ('element', )

sapeim/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
#importo a formset :D
from django.forms.formsets import formset_factory
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from .forms import AddElementForm, AddBlandForm, UserProfileForm, UserForm
from .forms import PrestamoForm, DetalleForm, PrestaForm
from .models import Element, Bland, UserProfile, Prestamo, DetallePrestamo, ElementType


class IndexView(ListView):
    model = Element
    template_name = 'sapeim/index.html'
    context_object_name = 'elemento'


class AddElement(CreateView):
    form_class = AddElementForm
    template_name = 'sapeim/admin/add_elemento.html'
    success_url = '/'


class UpdateElement(UpdateView):
    form_class = AddElementForm
    model = Element
    template_name = 'sapeim/admin/edit_element.html'
    #fields = ('bland', 'element_type', 'serial', 'serial_sena', 'modelo', 'features')
    # esta funcion es para que me deje en la misma url donde me encuentro :D

    def get_success_url(self):
    # esta funcion es para que me deje en la misma url donde me encuentro :D
        return self.request.path


class DeleteElement(DeleteView):
    #form_class = AddElementForm
    model = Element
    template_name = 'sapeim/admin/delete_element.html'
    success_url = '/'


class ListBland(ListView):
    model = Bland
    template_name = 'sapeim/admin/list_bland.html'
    context_object_name = 'lista'


class AddBland(CreateView):
    form_class = AddBlandForm
    success_url = 'sapeim:list-bland'
    template_name = 'sapeim/admin/add_bland.html'
# falta hacer el update de marcas


class DeleteBland(DeleteView):
    model = Bland
    success_url = 'sapeim:list-bland'
    template_name = 'sapeim/admin/delete_element.html'
    context_object_name = 'lista'


class ListElementType(ListView):
    model = ElementType
    template_name = 'sapeim/admin/list_type.html'
    context_object_name = "tipo"


class AddElementType(CreateView):
    model = ElementType
    success_url = "sapeim:list-type"
    template_name = 'sapeim/admin/add_type.html'
    fields = ('element_type',)


class DeleteElementType(DeleteView):
    model = ElementType
    success_url = 'sapeim:list_type'
    template_name = 'sapeim/admin/delete_element.html'
    context_object_name = 'type'
#falta hacer el update de tipo de elemento


def registro(request):
    if request.method == 'POST':
        user_pro = UserProfileForm(request.POST)
        user_u = UserForm(request.POST)
        if user_u.is_valid() and user_u.is_valid():
            user = user_u.save()
            user.set_password(user.password)#encrypto la pass
            user.save()
            profile_u = user_pro.save(commit=False)
            profile_u.username = user
            profile_u.save()
            return redirect('/')
        else:
            print("error")
    else:
        user_u = UserForm()
        user_pro = UserProfileForm()
    return render(request, 'sapeim/admin/registro.html', {'user': user_u, 'profile': user_pro})


class ListPrestamo(ListView):
    model = Prestamo
    template_name = 'sapeim/admin/list_prestamos.html'
    context_object_name = 'prestmos'
    queryset = Prestamo.objects.filter(devolucion=False)


class DetailPrestamo(DetailView):
    model = Prestamo
    template_name = 'sapeim/admin/detail_prestamo.html'

    def get_context_data(self, **kwargs):
            # Call the base implementation first to get a context
            context = super(DetailPrestamo, self).get_context_data(**kwargs)
             #Add in a QuerySet of all the books
            context['elemento'] = DetallePrestamo.objects.filter()
            return context


def prestamo(request):
    query = request.POST.get('documento')
    print(query)
    if request.method == 'POST':
        user_pro = UserProfile.objects.get(documento=query)
        prestamo = PrestaForm(request.POST)
        detail = DetalleForm(request.POST)

        if prestamo.is_valid() and detail.is_valid():
            detalle = detail.save(commit=False)
            elemento = Element.objects.get(modelo=detalle.element)
            if elemento.state == 2:
                return HttpResponse('este elemento ya esta prestado :D')
            else:
                presta = prestamo.save(commit=False)
                presta.user = user_pro
                presta.save()
                elemento.state = 2
                elemento.save()
                detalle.prestamo = presta
                detalle.save()
        else:
            print("hola")
        return redirect('sapeim:prestamos')
    else:
        prestamo = PrestaForm()
        detail = DetalleForm()
    return render(request, 'sapeim/admin/prestamo.html', {'prestamo': prestamo, 'detalle': detail})


def devolucion(request, **kwargs):
    pk = kwargs.get('pk')
    prestamo = Prestamo.objects.get(pk=pk)
    detalle = DetallePrestamo.objects.get(prestamo=pk)
    if request.method == 'POST':
        presta = PrestamoForm(request.POST, instance=prestamo)
        if presta.is_valid():
            pres = presta.save(commit=False)
            if pres.devolucion:
                elemento = Element.objects.get(modelo=detalle.element)
                elemento.state = 1
                elemento.save()
                pres.save()
                return redirect('sapeim:prestamos')
    else:
        presta = PrestamoForm(instance=prestamo)
    return render(request, 'sapeim/admin/devoluciones.html', {'prestamo': presta, 'detalle': detalle})

sapeim/templates/sapeim/admin/add_bland.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Añadir Marca</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

sapeim/templates/sapeim/admin/add_elemento.html
{% extends "base.html" %} 

{% block title %}
    Add Element
{% endblock %}

{% block content %}
    <h1>Hola a todos</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
       <input type="submit" value="enviar">
    </form>
{% endblock content %}

sapeim/templates/sapeim/admin/add_type.html
{% extends "sapeim/base_sapeim.html" %}

{% block content %}
    {% include "sapeim/admin/nav.html" %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button>Añadir</button>
        </form>
    </div>
{% endblock content %}

sapeim/templates/sapeim/admin/delete_element.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sapeim</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}

        
        {% if lista %}
            <p>Seguro qe quieres eliminar  la marca {{lista.bland_name}}</p>
            {% else %}
                
        {% endif %}
        {% if type %}
            <p>Seguro qe quieres eliminar el tipo de elemento {{type.element_type}}</p>
            {% else %}
                <p>Seguro qe quieres eliminar el elemento {{object.modelo}}</p>
        {% endif %}
        <input type="submit" value="eliminar">
    </form>
</body>
</html>

sapeim/templates/sapeim/admin/detail_prestamo.html
{% extends "sapeim/base_sapeim.html" %}
{% block content %}
    {% include "sapeim/admin/nav.html" %}
    <div class="container">
        <p>Nombre del instructor: {{object.user}}</p>
        <p>hora inicio: {{object.hora_inicio}}</p>
        <p>hora entrega: {{object.hora_fin}}</p>
        <p>Elementos: <ul>
            {% for elementos in elemento %}
                <li>{{elementos.element.bland}}-{{elementos.element}}-{{elementos.element.serial_sena}}</li>
            {% endfor %}
        </ul></p>
    </div>
{% endblock content %}

sapeim/templates/sapeim/admin/devoluciones.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Devoluciones</title>
</head>
<body>
    <form method="post">
        <p>Elemento: {{detalle.element}}</p>
        {% csrf_token %}
        {{prestamo.as_p}}
        <button>Devolver</button>
    </form>
    
</body>
</html>

sapeim/templates/sapeim/admin/edit_element.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sapeim</title>
</head>
<body>
    <form  method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Actualizar">
    </form>
</body>
</html>

sapeim/templates/sapeim/admin/list_bland.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista De Marcas</title>
</head>
<body>
    <h1>Listas de Marcas</h1>
    {% for marcas in lista %}
        <ul>
            <li>{{ marcas }} <a href="{% url 'sapeim:delete-bland/{{ marcas.id }}' %}">Eliminar</a></li>
        </ul>
    {% endfor %}
    <a href="add-bland">Añadir marca</a>
</body>
</html>

sapeim/templates/sapeim/admin/list_prestamos.html
{% extends "sapeim/base_sapeim.html" %}
{% block content %}
    {% include "sapeim/admin/nav.html" %}
    <div class="container">
        <ul>
            {% for prestamo in prestmos %}
                <a href="{% url 'sapeim:detail-prestamo/{{prestamo.id}}' %}"><li>{{ prestamo.user.nombre }} {{ prestamo.user.apellido }}</li></a><a href="{% url 'sapeim:devoluciones/{{prestamo.id}}' %}">devolver</a>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}
    

sapeim/templates/sapeim/admin/list_type.html
{% extends "sapeim/base_sapeim.html" %}

{% block content %}
    {% include "sapeim/admin/nav.html" %}
    <div class="container">
        {% for type in tipo %}
            <ul>
                <li>{{ type }}<a href="{% url 'sapeim:delete-type/{{ type.id }}' %}">Eliminar</a></li>
            </ul>
        {% endfor %}
    </div>
    
{% endblock content %}

sapeim/templates/sapeim/admin/nav.html
    <header>
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navegacion-fm">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a href="/" class="navbar-brand">Sapeim</a>
              </div>
              <!--Inicia Menu-->
              <div class="collapse navbar-collapse" id="navegacion-fm">
                  <ul class="nav navbar-nav">
                      <li class="active"><a href="/">Inicio</a></li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="botton">
                            Prestamos <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" role="menu">
                              {#<li><a href="{% url 'sapeim:prestamos' %}">Ver prestamos</a></li>#}
                              <li class="divider"></li>
                              <li><a href="{% url 'sapeim:add-prestamo' %}">Agregar prestamos</a></li>
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="botton">
                            Tipo elementos <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" role="menu">
                              <li><a href="{% url 'sapeim:list-type' %}">Ver tipos</a></li>
                              <li class="divider"></li>
                              <li><a href="{% url 'sapeim:add-type' %}">Agregar tipos</a></li>
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="botton">
                            Marcas <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" role="menu">
                              <li><a href="{% url 'sapeim:list-bland' %}">Ver marcas</a></li>
                              <li class="divider"></li>
                              <li><a href="{% url 'sapeim:add-bland' %}">Agregar marcas</a></li>
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="botton">
                            Elementos <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" role="menu">
                              <li><a href="#">Ver Elementos</a></li>
                              <li class="divider"></li>
                              <li><a href="{% url 'sapeim:add-elemento' %}">Agregar Elementos</a></li>
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="botton">
                            Usuarios <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" role="menu">
                              <li><a href="#">Ver Usuarios</a></li>
                              <li class="divider"></li>
                              <li><a href="{% url 'sapeim:registro' %}">Agregar Usuarios</a></li>
                          </ul>
                      </li>
                      
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                         <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bienvenido / {{request.user}} <span class="caret"></span></a>
                           <ul class="dropdown-menu">
                             <li><a href="#">Cerrar Sesion</a></li>
                             <li role="separator" class="divider"></li>
                             <li><a href="#">Separated link</a></li>
                           </ul>
                         </li>
                       </ul>
              </div>
            </div>
        </nav>
    </header>

sapeim/templates/sapeim/admin/prestamo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prestamos</title>
</head>
<body>
    <h1>Prestamos</h1>
    <form method="POST">
        {% csrf_token %}
        
        {{prestamo.as_p}}
        <p>Elemento: {{detalle.element}}</p>
        <input type="number" name="documento">
        <button>Prestar</button>
    </form>
</body>
</html>

sapeim/templates/sapeim/admin/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registro de </title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{user.as_p}}
        {{profile.as_p}}
        <button>Registrar</button>
    </form>
</body>
</html>